profiles:
    bh22-win-111:
        connector: elastic_ecs
        connection:
            host: localhost
            port: 9234
            selfSignedCert: false
            indices: win-111-winlogbeat-bh22-20220727
            options:
                dialects:
                  - beats
        config:
            auth:
                username: elastic
                password: <ES_PWD>
    bh22-win-112:
        connector: elastic_ecs
        connection:
            host: localhost
            port: 9234
            selfSignedCert: false
            indices: win-112-winlogbeat-bh22-20220727
            options:
                dialects:
                  - beats
        config:
            auth:
                username: elastic
                password: <ES_PWD>
    bh22-linux:
        connector: elastic_ecs
        connection:
            host: localhost
            port: 9234
            selfSignedCert: false
            indices: linux-91-sysflow-bh22-20220727
            options:
                dialects:
                  - beats
        config:
            auth:
                username: elastic
                password: <ES_PWD>
    win-500k:
        connector: elastic_ecs
        connection:
            host: localhost
            port: 9234
            selfSignedCert: false
            indices: win-52-elasticagent-500k-benign-20230523
            options:
              result_limit: 500000
              retrieval_batch_size: 10000
        config:
            auth:
                username: elastic
                password: <ES_PWD>